In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

In [3]:
a=([[1,2],[3,4]])
print(a)

[[1, 2], [3, 4]]


In [4]:
b=np.array(a)
print(b)

[[1 2]
 [3 4]]


In [5]:
b.ndim

2

In [6]:
b.shape

(2, 2)

In [7]:
b.size

4

In [8]:
b.itemsize

4

In [9]:
b.dtype

dtype('int32')

In [10]:
b.data

In [17]:
c=np.array([[[9.0,5.0,4.0]],[[6.0,3.0,8.0]]])
print(c)

[[[9. 5. 4.]]

 [[6. 3. 8.]]]


In [18]:
c.ndim

3

In [19]:
c.dtype

dtype('float64')

In [20]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#get specfic element
d[1,5]

13

In [25]:
#get specfic row
d[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#get specfic column
d[:, 3]

array([ 4, 11])

In [30]:
#get little More Fancy[startindex:endindex:stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [38]:
d[:,2]=[1,2]
print(d)

d[0,5]=20
print(d)

print(d)

[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]


In [39]:
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
#get specfic element(work outside in)
e[0,1,1]

4

In [44]:
#All 0s Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [54]:
#Any Another Number
np.full((2,2),45, dtype='float32')

array([[45., 45.],
       [45., 45.]], dtype=float32)

In [60]:
#Any Another Number(Full_Like)
np.full_like(d.shape,4)

array([4, 4])

In [62]:
#Random Decimal Number
np.random.rand(4,2)

array([[0.55922741, 0.47182795],
       [0.6015612 , 0.06359354],
       [0.76539038, 0.48080156],
       [0.11298569, 0.90573307]])

In [69]:
#Random Integer Value
np.random.randint(4,8, size=(3,3))

array([[6, 7, 4],
       [5, 4, 6],
       [4, 7, 6]])

In [ ]:
#Repeat Array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)