In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

In [3]:
a=([[1,2],[3,4]])
print(a)

[[1, 2], [3, 4]]


In [4]:
b=np.array(a)
print(b)

[[1 2]
 [3 4]]


In [5]:
b.ndim

2

In [6]:
b.shape

(2, 2)

In [7]:
b.size

4

In [8]:
b.itemsize

4

In [9]:
b.dtype

dtype('int32')

In [10]:
b.data

In [17]:
c=np.array([[[9.0,5.0,4.0]],[[6.0,3.0,8.0]]])
print(c)

[[[9. 5. 4.]]

 [[6. 3. 8.]]]


In [18]:
c.ndim

3

In [19]:
c.dtype

dtype('float64')

In [20]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#get specfic element
d[1,5]

13

In [25]:
#get specfic row
d[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#get specfic column
d[:, 3]

array([ 4, 11])

In [30]:
#get little More Fancy[startindex:endindex:stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [38]:
d[:,2]=[1,2]
print(d)

d[0,5]=20
print(d)

print(d)

[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]


In [39]:
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
#get specfic element(work outside in)
e[0,1,1]

4

In [44]:
#All 0s Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [54]:
#Any Another Number
np.full((2,2),45, dtype='float32')

array([[45., 45.],
       [45., 45.]], dtype=float32)

In [60]:
#Any Another Number(Full_Like)
np.full_like(d.shape,4)

array([4, 4])

In [62]:
#Random Decimal Number
np.random.rand(4,2)

array([[0.55922741, 0.47182795],
       [0.6015612 , 0.06359354],
       [0.76539038, 0.48080156],
       [0.11298569, 0.90573307]])

In [69]:
#Random Integer Value
np.random.randint(4,8, size=(3,3))

array([[6, 7, 4],
       [5, 4, 6],
       [4, 7, 6]])

In [ ]:
#Repeat Array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

In [5]:
import numpy as np


In [15]:
f=np.array([[1,3,2],[5,4,6]])
print(f)

[[1 3 2]
 [5 4 6]]


In [16]:
#copying Array
g=np.copy(f)
print(g)

[[1 3 2]
 [5 4 6]]


In [17]:
#View
f.view(dtype='float32')


array([[1.e-45, 4.e-45, 3.e-45],
       [7.e-45, 6.e-45, 8.e-45]], dtype=float32)

In [19]:
#Sorting
f.sort()
print(f)

[[1 2 3]
 [4 5 6]]


In [22]:
#sorting based on axis
f.sort(axis=1)
print(f)

[[1 2 3]
 [4 5 6]]


In [31]:
#reshape
h=f.reshape(1,6)
print(h)

[[1 2 3 4 5 6]]


In [34]:
#append
i=np.append(f,[7,8,9])
print(i)

[1 2 3 4 5 6 7 8 9]


In [36]:
#Insert Array at any Index
j=np.insert(f,4,16)
print(j)

[ 1  2  3  4 16  5  6]


In [44]:
print(f)
k=np.delete(f,0,axis=1)
print(k)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [52]:
#Contacation
a1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a2=np.array([[13,14,15,16,17,18],[19,20,21,22,23,24]])
c=np.concatenate((a1,a2),axis=1)
print(c)

[[ 1  2  3  4  5  6 13 14 15 16 17 18]
 [ 7  8  9 10 11 12 19 20 21 22 23 24]]


In [70]:
#Split Array
a3=np.array([1,2,3,4,5,6])
print(a3)
d=np.split(a3,3)
print(d)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [68]:
#Indexing/subsetting
a3[2]

3

In [74]:
#slicing
print(a3)
a3[2:3]

[1 2 3 4 5 6]


array([3])

In [79]:
#slicing
#[sart:stop:step]
print(c)
c[:,2]

[[ 1  2  3  4  5  6 13 14 15 16 17 18]
 [ 7  8  9 10 11 12 19 20 21 22 23 24]]


array([3, 9])

In [2]:
import numpy as np


In [6]:
m=np.array([1,2,3])

print(m)

[1 2 3]


***Mathematics***


In [8]:
m=np.array([1,2,3,4])
print(m)

[1 2 3 4]


In [9]:
#Addtion of array by specify element
m+2


array([3, 4, 5, 6])

In [10]:
#Substraction of array by specify element
m-2

array([-1,  0,  1,  2])

In [11]:
#Multiplication of array by specify element
m*2

array([2, 4, 6, 8])

In [12]:
#Division of array by specify element
m/2

array([0.5, 1. , 1.5, 2. ])

In [14]:
n=np.array([1,0,1,0])
m+n

array([2, 0, 2, 0])

In [16]:
m ** n

array([1, 1, 1, 1], dtype=int32)

In [18]:
#Addition of two 1d array
o=np.array([1,2,3])
p=np.array([4,5,6])
q=np.add(o,p)
print(q)

[5 7 9]


In [19]:
#Substraction of two 1d array
q=np.subtract(p,o)
print(q)

[3 3 3]


In [20]:
#Multiplication of two 1d array
q=np.multiply(o,p)
print(q)

[ 4 10 18]


In [22]:
#Divison of two 1d array
q=np.divide(o,p)
print(q)

[0.25 0.4  0.5 ]


In [25]:
#Exponentinal
#q=np.exp(o)
q=np.exp(p)
print(q)

[ 54.59815003 148.4131591  403.42879349]


In [27]:
#SquareRoot
#q=np.sqrt(o)
q=np.sqrt(p)
print(q)

[2.         2.23606798 2.44948974]


In [29]:
#Comparsion
r=([1,2,3])
s=([1,2,3])
r==s

True

In [34]:
#Array wise comparsion
t=np.array_equal(r,s)
# t=np.array_equal(o,p)
print(t)

True


***Functions***


In [44]:
u=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(u)


[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [46]:
u.sum()

42

In [48]:
u.sum(axis=0)

array([11, 14, 17])

In [50]:
u.min()

1

In [51]:
u.max()

8

In [52]:
u.mean()

4.666666666666667

In [54]:
u.sum(axis=1)

array([ 6, 15, 21])

In [56]:
v=np.array([[10,7,4],[3,2,1]])
v

array([[10,  7,  4],
       [ 3,  2,  1]])

In [58]:
w=np.median(v)
print(w)

3.5


In [60]:
w=np.median(v,axis=0)
print(w)

[6.5 4.5 2.5]


In [62]:
w=np.median(v,axis=1)
print(w)

[7. 2.]


In [68]:
from scipy import stats as st

In [69]:
arr1=([9,8,7,6,6,7,5,4,1,1,1,1,3,2,2,3])
print(st.mode(arr1))

ModeResult(mode=array([1]), count=array([4]))


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2272\131236005.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(arr1))
