In [1]:
import numpy as np


In [3]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])


In [4]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
#Horizontal Stack
c=np.hstack((a,b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [8]:
#Vertical stack
d=np.vstack((a,b))
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#arange
e=np.arange(1,11)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Arrange with Steps
f=np.arange(2,21,2)
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
#Table
g=np.arange(13,131,13)
g

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [14]:
#linspace
h=np.linspace(1.0,5.0,num=10)
h

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
#Indexing and Slicing
# i=a[0:1] ##firstrow
i=a[1:2] ##secondrow
print(i)

[[4 5 6]]


In [32]:
# j=a[:,2]
j=a[0:1,2]  ##last element
print(j)

[3]


In [46]:
k=np.zeros((4,4))
print(k)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
l=np.eye(3)
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
m=np.random.randint(0,10,size=(3,2))
m


array([[0, 7],
       [0, 4],
       [3, 9]])

In [38]:
n=np.array([1,2,3,4,5])
n +=5
print(n)

[ 6  7  8  9 10]


In [42]:
o=np.random.randint(0,10,size=(3,3))
print(o)
# print(o.min())
# print(o.max())
print(o.sum())


[[5 2 5]
 [5 6 9]
 [0 1 6]]
39


In [47]:
p=np.random.randint(0,10,size=(3,3))
print(p)
print(p.shape)
print("After Reshape")
q=p.reshape(9,1)
print(q)

[[4 5 4]
 [0 1 2]
 [4 7 8]]
(3, 3)
After Reshape
[[4]
 [5]
 [4]
 [0]
 [1]
 [2]
 [4]
 [7]
 [8]]


In [48]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])
a3=np.add(a1,a2)
print(a3)

[[ 8 10 12]
 [14 16 18]]


In [52]:
a4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a4)
print("After Swap")
a4=a4.T
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Swap
[[1 4 7]
 [2 5 8]
 [3 6 9]]
