In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
ti=pd.read_csv('tested.csv')
ti

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [6]:
ti.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
ag = ti['Age']
print(type(ag))

<class 'pandas.core.series.Series'>


In [10]:
agmean = ag.mean()

In [11]:
ag.fillna(agmean,inplace=True)

In [12]:
ti.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [18]:
fa=ti['Fare']
fa

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...   
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [19]:
famean=fa.mean()

In [20]:
fa.fillna(famean,inplace=True)

In [21]:
ti['Fare'].value_counts()

7.7500     21
26.0000    19
8.0500     17
13.0000    17
10.5000    11
           ..
8.7125      1
7.8208      1
8.5167      1
78.8500     1
22.3583     1
Name: Fare, Length: 170, dtype: int64

In [22]:
ti.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [27]:
dr=ti.drop(columns=['Cabin','Ticket','Name'])

In [28]:
dr

PassengerId  Survived  Pclass     Sex       Age  SibSp  Parch      Fare  \
0            892         0       3    male  34.50000      0      0    7.8292   
1            893         1       3  female  47.00000      1      0    7.0000   
2            894         0       2    male  62.00000      0      0    9.6875   
3            895         0       3    male  27.00000      0      0    8.6625   
4            896         1       3  female  22.00000      1      1   12.2875   
..           ...       ...     ...     ...       ...    ...    ...       ...   
413         1305         0       3    male  30.27259      0      0    8.0500   
414         1306         1       1  female  39.00000      0      0  108.9000   
415         1307         0       3    male  38.50000      0      0    7.2500   
416         1308         0       3    male  30.27259      0      0    8.0500   
417         1309         0       3    male  30.27259      1      1   22.3583   

    Embarked  
0          Q  
1          S  
2          Q  
3          S  
4          S  
..       ...  
413        S  
414        C  
415        S  
416        S  
417        C  

[418 rows x 9 columns]

In [29]:
dr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 29.5+ KB


In [36]:
ti['Fare']=dr['Fare'].astype('int64')
ti['Fare']

0        7
1        7
2        9
3        8
4       12
      ... 
413      8
414    108
415      7
416      8
417     22
Name: Fare, Length: 418, dtype: int64

In [37]:
ti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         418 non-null    int64  
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(1), int64(6), object(5)
memory usage: 39.3+ KB


In [39]:
ti['Age']=dr['Age'].astype('int64')
ti["Age"]

0      34
1      47
2      62
3      27
4      22
       ..
413    30
414    39
415    38
416    30
417    30
Name: Age, Length: 418, dtype: int64

In [40]:
ti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   PassengerId  418 non-null    int64 
 1   Survived     418 non-null    int64 
 2   Pclass       418 non-null    int64 
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    int64 
 6   SibSp        418 non-null    int64 
 7   Parch        418 non-null    int64 
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    int64 
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: int64(7), object(5)
memory usage: 39.3+ KB


In [50]:
dro=ti.drop(columns=['Name','Ticket','Cabin','Sex'])

In [51]:
dro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   PassengerId  418 non-null    int64 
 1   Survived     418 non-null    int64 
 2   Pclass       418 non-null    int64 
 3   Age          418 non-null    int64 
 4   SibSp        418 non-null    int64 
 5   Parch        418 non-null    int64 
 6   Fare         418 non-null    int64 
 7   Embarked     418 non-null    object
dtypes: int64(7), object(1)
memory usage: 26.2+ KB


In [52]:
dro['Embarked'].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [54]:
x=dro.iloc[:,0:6].values
x

array([[ 892,    0,    3,   34,    0,    0],
       [ 893,    1,    3,   47,    1,    0],
       [ 894,    0,    2,   62,    0,    0],
       ...,
       [1307,    0,    3,   38,    0,    0],
       [1308,    0,    3,   30,    0,    0],
       [1309,    0,    3,   30,    1,    1]], dtype=int64)

In [57]:
y=dro.iloc[:,7].values
y

array(['Q', 'S', 'Q', 'S', 'S', 'S', 'Q', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'C', 'Q', 'C', 'S', 'C', 'C', 'S', 'S', 'C', 'C', 'S',
       'C', 'C', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S',
       'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'C', 'S', 'S', 'C',
       'S', 'S', 'C', 'Q', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'Q', 'C',
       'S', 'Q', 'S', 'C', 'S', 'Q', 'S', 'S', 'C', 'C', 'C', 'S', 'S',
       'S', 'Q', 'C', 'S', 'S', 'S', 'Q', 'C', 'Q', 'S', 'Q', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'Q', 'S',
       'C', 'S', 'Q', 'Q', 'S', 'S', 'C', 'Q', 'C', 'Q', 'S', 'C', 'C',
       'S', 'C', 'S', 'S', 'Q', 'C', 'S', 'Q', 'S', 'S', 'Q', 'S', 'S',
       'S', 'C', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'Q', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'C',
       'S', 'S', 'C', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'C', 'S

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
labelencoder_y = LabelEncoder()

In [61]:
labelencoder_y.fit_transform(y)

array([1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 2,
       0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2,
       2, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2,
       0, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2,
       2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2,

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [66]:
print(x_train.size)
print(x_test.size)
print(y_train.size)
print(x_test.size)

1752
756
292
756


In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
logModel = LogisticRegression()
logModel.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [69]:
y_pred_log = logModel.predict(x_test)

In [70]:
y_pred_log

array(['S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'C',
       'S', 'S', 'S', 'Q', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q',
       'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [71]:
from sklearn.metrics import confusion_matrix

In [72]:
 confusion_matrix(y_test,y_pred_log)

array([[ 4,  0, 19],
       [ 1,  2, 11],
       [ 7,  2, 80]], dtype=int64)

In [73]:
logModel.score(x_test,y_test)

0.6825396825396826

In [74]:
from sklearn.neighbors import KNeighborsClassifier

In [76]:
knc = KNeighborsClassifier()
knc.fit(x_train,y_train)

KNeighborsClassifier()

In [78]:
y_pred_kn = knc.predict(x_test)
y_pred_kn 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array(['S', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'C', 'S', 'S', 'S', 'Q', 'C', 'S', 'C', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'C', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'C',
       'Q', 'S', 'S', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S',
       'S', 'Q', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'C', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S',
       'S', 'S', 'C', 'S', 'S', 'Q', 'S', 'S', 'S', 'C', 'S', 'S', 'S',
       'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'Q',
       'C', 'C', 'S', 'S', 'S', 'C', 'C', 'C', 'C'], dtype=object)

In [79]:
confusion_matrix(y_test,y_pred_kn)

array([[ 4,  1, 18],
       [ 2,  2, 10],
       [20,  5, 64]], dtype=int64)

In [80]:
knc.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.5555555555555556

In [83]:
from sklearn.naive_bayes import GaussianNB

In [85]:
nav=GaussianNB()
nav.fit(x_train,y_train)

GaussianNB()

In [86]:
y_pred_na = nav.predict(x_test)

In [87]:
confusion_matrix(y_test,y_pred_na)

array([[13,  4,  6],
       [ 3, 11,  0],
       [18, 33, 38]], dtype=int64)

In [88]:
nav.score(x_test,y_test)

0.49206349206349204

In [89]:
from sklearn.metrics import accuracy_score

In [90]:
accuracy_score(y_pred_na,y_test)

0.49206349206349204

In [91]:
from sklearn.svm import SVC

In [94]:
sv = SVC(kernel = "sigmoid")
sv.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [95]:
y_pred_s=sv.predict(x_test)

In [96]:
y_pred_s

array(['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [97]:
confusion_matrix(y_test,y_pred_s)

array([[ 0,  0, 23],
       [ 0,  0, 14],
       [ 0,  0, 89]], dtype=int64)

In [98]:
sv.score(x_test,y_test)

0.7063492063492064

In [99]:
sv1 = SVC(kernel = "poly")
sv1.fit(x_train,y_train)

SVC(kernel='poly')

In [100]:
y_pred_sv1 =sv1.predict(x_test)

In [101]:
confusion_matrix(y_test,y_pred_sv1)

array([[ 0,  0, 23],
       [ 0,  0, 14],
       [ 0,  0, 89]], dtype=int64)

In [102]:
sv1.score(x_test,y_test)

0.7063492063492064

In [104]:
sv2 = SVC(kernel = "rbf")
sv2.fit(x_train,y_train)

SVC()

In [105]:
y_pred_sv2=sv2.predict(x_test)

In [106]:
confusion_matrix(y_test,y_pred_sv2)

array([[ 0,  0, 23],
       [ 0,  0, 14],
       [ 0,  0, 89]], dtype=int64)

In [107]:
sv2.score(x_test,y_test)

0.7063492063492064

In [108]:
from sklearn.neighbors import KNeighborsClassifier

In [111]:
k_clas=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
k_clas.fit(x_train,y_train)

KNeighborsClassifier()

In [112]:
y_pred_knn=k_clas.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [113]:
confusion_matrix(y_test,y_pred_knn)

array([[ 4,  1, 18],
       [ 2,  2, 10],
       [20,  5, 64]], dtype=int64)

In [114]:
k_clas.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.5555555555555556

In [115]:
from sklearn.metrics import accuracy_score

In [116]:
accuracy_score(y_test,y_pred_knn)

0.5555555555555556